"""Increase text lengths

Revision ID: 158b958d3e29
Revises: 817805639f4a
Create Date: 2026-06-16 19:21:50.902356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '158b958d3e29'
down_revision: Union[str, Sequence[str], None] = '817805639f4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('experience_bullets', 'text',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=300),
               existing_nullable=False)
    op.alter_column('experiences', 'role',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('project_bullets', 'text',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=300),
               existing_nullable=False)
    op.alter_column('projects', 'description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=300),
               existing_nullable=False)
    op.alter_column('technical_bullets', 'text',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=300),
               existing_nullable=False)
    op.alter_column('technical_skills', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('technical_skills', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('technical_bullets', 'text',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.alter_column('projects', 'description',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('project_bullets', 'text',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.alter_column('experiences', 'role',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('experience_bullets', 'text',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    # ### end Alembic commands ###
